SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS euros, precio AS USD FROM producto;
SELECT nombre AS 'nom de producto', precio AS euros, precio AS dòlars FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTR(nombre,1,2)) AS siglas FROM fabricante;
SELECT nombre, ROUND(precio) AS 'precio redondeado' FROM producto;
SELECT nombre, CAST(precio AS UNSIGNED) AS 'precio truncado' FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo order by nombre_fabricante;
SELECT p.codigo, p.nombre, p.codigo_fabricante, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY precio ASC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY precio DESC LIMIT 1;
SELECT p.codigo, p.nombre, p.precio, codigo_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Lenovo";
SELECT p.codigo, p.nombre, p.precio, p.codigo_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Crucial" AND p.precio > 200;
SELECT p.codigo, p.nombre, p.precio, p.codigo_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Asus" OR f.nombre = "Hewlett-Packard" OR f.nombre = "Seagate";
SELECT p.codigo, p.nombre, p.precio, p.codigo_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN("Asus","Hewlett-Packard","Seagate");
SELECT p.nombre, p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
SELECT p.nombre, p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo, f.nombre FROM fabricante f INNER JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.codigo, f.nombre, p.codigo, p.nombre, p.precio FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.codigo, f.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo");
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT nombre FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT nombre FROM producto WHERE precio = (SELECT MIN(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Hewlett-Packard"));
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Lenovo"));
SELECT * FROM producto WHERE precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = "Asus"));
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = "alumno" ORDER BY apellido1, apellido2, nombre ASC;
SELECT nombre, apellido1, apellido2 FROM persona WHERE telefono IS NULL AND tipo = "alumno";
SELECT * FROM persona WHERE fecha_nacimiento BETWEEN "1999-01-01" AND "1999-12-31";
SELECT * FROM persona WHERE tipo = "profesor" AND telefono IS NULL AND nif LIKE '%K';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT p.apellido1, p.apellido2, p.nombre, d.nombre AS nombre_departamento FROM persona p INNER JOIN profesor pf ON p.id = pf.id_profesor INNER JOIN departamento d ON pf.id_departamento = d.id ORDER BY p.apellido1, p.apellido2, p.nombre ASC;
SELECT a.nombre, c.anyo_inicio, c.anyo_fin FROM asignatura a INNER JOIN alumno_se_matricula_asignatura aa ON a.id = aa.id_asignatura INNER JOIN curso_escolar c ON aa.id_curso_escolar = c.id INNER JOIN persona p ON aa.id_alumno = p.id WHERE p.nif = "26902806M";
SELECT d.nombre FROM departamento d INNER JOIN profesor pf ON d.id = pf.id_departamento WHERE pf.id_profesor = (SELECT id_profesor FROM asignatura WHERE id = (SELECT id FROM grado WHERE nombre = "Grado en Ingeniería Informática (Plan 2015)"));
SELECT DISTINCT p.* FROM persona p INNER JOIN alumno_se_matricula_asignatura aa ON p.id = aa.id_alumno WHERE aa.id_curso_escolar = (SELECT id FROM curso_escolar WHERE anyo_inicio = "2018" AND anyo_fin = "2019");
SELECT d.nombre AS nombre_departamento, p.apellido1, p.apellido2, p.nombre FROM persona p RIGHT JOIN profesor pf ON p.id = pf.id_profesor LEFT JOIN departamento d ON pf.id_departamento = d.id ORDER BY d.nombre, p.apellido1, p.apellido2, p.nombre ASC;
SELECT * FROM persona p RIGHT JOIN profesor pf ON p.id = pf.id_profesor WHERE pf.id_departamento IS NULL;
SELECT d.* FROM departamento d LEFT JOIN profesor pf ON d.id = pf.id_departamento WHERE pf.id_profesor IS NULL;
SELECT * FROM persona p LEFT JOIN asignatura a ON p.id = a.id_profesor WHERE p.tipo = "profesor" AND a.id_profesor IS NULL;
SELECT * FROM asignatura WHERE id_profesor IS NULL;
SELECT DISTINCT d.* FROM departamento d LEFT JOIN profesor pf ON d.id = pf.id_departamento LEFT JOIN asignatura a ON pf.id_profesor = a.id_profesor WHERE a.id_grado IS NULL;
SELECT COUNT(id) FROM persona WHERE tipo = "alumno";
SELECT COUNT(id) FROM persona WHERE tipo = "alumno" AND fecha_nacimiento BETWEEN "1999-01-01" AND "1999-12-31";
SELECT d.nombre, COUNT(pf.id_departamento) AS num_profesors FROM profesor pf INNER JOIN departamento d ON pf.id_departamento = d.id GROUP BY d.nombre ORDER BY num_profesors DESC;
SELECT d.*, COUNT(pf.id_departamento) AS num_profesors FROM departamento d LEFT JOIN profesor pf ON d.id = pf.id_departamento GROUP BY d.nombre;
SELECT g.*, COUNT(a.id) AS num_assignatures FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre ORDER BY num_assignatures DESC;
SELECT g.*, COUNT(a.id) AS num_assignatures FROM grado g INNER JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre HAVING num_assignatures > 40;
SELECT g.nombre, a.tipo, SUM(a.creditos) AS total_credits FROM grado g INNER JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre, a.tipo;
SELECT c.anyo_inicio, COUNT(p.id) AS alumnes_matriculats FROM persona p INNER JOIN alumno_se_matricula_asignatura aa ON p.id = aa. id_alumno INNER JOIN curso_escolar c ON aa.id_curso_escolar = c.id GROUP BY c.anyo_inicio;
SELECT p.id, p.nombre, p.apellido1, p.apellido2, COUNT(a.id) AS num_assignatures FROM persona p LEFT JOIN asignatura a ON p.id = a.id_profesor WHERE p.tipo = "profesor" GROUP BY p.id ORDER BY num_assignatures DESC;
SELECT * FROM persona WHERE tipo = "alumno" ORDER BY fecha_nacimiento DESC LIMIT 1;
SELECT * FROM persona p INNER JOIN profesor pf ON p.id = pf.id_profesor  LEFT JOIN asignatura a ON p.id = a.id_profesor WHERE p.tipo = "profesor" AND a.id_profesor IS NULL;